import type { Profile } from "./profile";

// ── Status enums ────────────────────────────────────────────────────────────

export type CopyStatus = "available" | "borrowed" | "damaged";
export type TransactionType = "borrow" | "return";
export type TransactionStatus =
  | "pending"
  | "active"
  | "overdue"
  | "completed"
  | "rejected";
export type PdfSubmissionStatus = "pending" | "approved" | "rejected";

export type ActionLogType =
  | "user_joined"
  | "user_verified"
  | "user_unverified"
  | "role_changed"
  | "thana_deleted"
  | "error";

// ── Core entities ───────────────────────────────────────────────────────────

export interface Book {
  id: string; // UUID auto-generated by the database
  title: string;
  author: string;
  category_id: string | null;
  is_syllabus: boolean;
  pages: number | null;
  pdf_link: string | null;
  created_at: string;
  updated_at: string;
  // joined
  category?: Category;
  copies?: Copy[];
}

export interface Category {
  id: string;
  name: string;
  count_in_progress: boolean;
  created_at: string;
  updated_at: string;
}

export interface CategoryProgress {
  categoryId: string;
  categoryName: string;
  completed: number;
  total: number;
}

export interface Copy {
  id: string; // QR code text, e.g. "QR001"
  book_id: string;
  copy_number: number;
  status: CopyStatus;
  created_at: string;
  updated_at: string;
  // joined
  book?: Pick<
    Book,
    "id" | "title" | "author" | "is_syllabus" | "pages" | "pdf_link"
  >;
  // computed
  borrower?: {
    id: string;
    full_name: string;
  } | null;
}

export interface Transaction {
  id: string;
  user_id: string;
  copy_id: string;
  book_id: string;
  type: TransactionType;
  status: TransactionStatus;
  request_date: string;
  approved_date: string | null;
  due_date: string | null;
  return_date: string | null;
  rejection_reason: string | null;
  reviewed_by: string | null;
  created_at: string;
  updated_at: string;
  // joined
  user?: Pick<
    Profile,
    "id" | "full_name" | "username" | "email" | "avatar_url" | "phone"
  >;
  copy?: Pick<Copy, "id" | "copy_number" | "status" | "book_id">;
  book?: Pick<Book, "id" | "title" | "author" | "is_syllabus" | "pdf_link">;
  reviewer?: Pick<Profile, "id" | "full_name">;
}

export interface PdfSubmission {
  id: string;
  user_id: string;
  book_id: string;
  read_date: string | null;
  note: string | null;
  status: PdfSubmissionStatus;
  submitted_at: string;
  reviewed_at: string | null;
  reviewed_by: string | null;
  rejection_reason: string | null;
  // joined
  user?: Pick<Profile, "id" | "full_name" | "username" | "avatar_url">;
  book?: Pick<Book, "id" | "title" | "author" | "is_syllabus" | "pdf_link">;
  reviewer?: Pick<Profile, "id" | "full_name">;
}

export interface ActionLog {
  id: string;
  action_type: ActionLogType;
  actor_id: string | null;
  target_id: string;
  details: string | null;
  created_at: string;
  // joined
  actor?: Pick<Profile, "id" | "full_name" | "username" | "avatar_url">;
  target?: Pick<Profile, "id" | "full_name" | "username" | "avatar_url">;
}

export interface NotificationItem {
  id: string;
  date: string;
  type:
    | "transaction_approved"
    | "transaction_rejected"
    | "transaction_completed"
    | "transaction_overdue"
    | "pdf_approved"
    | "pdf_rejected"
    | "user_verified"
    | "user_unverified"
    | "role_changed"
    | "thana_deleted"
    | "user_joined";
  title: string;
  message: string;
  link?: string;
  reason?: string | null;
}

// ── Aggregate / computed ─────────────────────────────────────────────────────

export interface UserStats {
  syllabusCompleted: number;
  syllabusTotal: number;
  categoryProgress: CategoryProgress[];
  activeBorrows: number;
  overdueBorrows: number;
  pendingRequests: number;
  currentBorrows: Transaction[];
}

export interface UserWithStats extends Profile {
  syllabusCompleted: number;
  syllabusTotal: number;
  categoryProgress: CategoryProgress[];
  activeBorrows: number;
  overdueBorrows: number;
  pendingRequests: number;
}

// ── Overview dashboard ───────────────────────────────────────────────────────

export interface OverviewStats {
  totalBooks: number;
  syllabusBooks: number;
  generalBooks: number;
  booksByCategory: { name: string; count: number }[];
  totalCopies: number;
  availableCopies: number;
  borrowedCopies: number;
  damagedCopies: number;
  totalMembers: number;
  verifiedMembers: number;
  unverifiedMembers: number;
  activeBorrows: number;
  overdueCount: number;
  pendingBorrowRequests: number;
  pendingReturnRequests: number;
  pendingPdfSubmissions: number;
  completedThisMonth: number;
}

export interface TopMember {
  id: string;
  full_name: string;
  username: string;
  avatar_url: string | null;
  totalBorrows: number;
}

export interface PopularBook {
  id: string;
  title: string;
  author: string;
  is_syllabus: boolean;
  category_name?: string;
  totalBorrows: number;
}

export interface OverviewData {
  stats: OverviewStats;
  overdueItems: Transaction[];
  pendingBorrows: Transaction[];
  pendingReturns: Transaction[];
  recentActivity: Transaction[];
  topMembers: TopMember[];
  popularBooks: PopularBook[];
  pendingPdfs: PdfSubmission[];
}
