"use server";

/**
 * server/library-actions.ts — Server Actions for book and copy CRUD.
 *
 * Caller must be admin or moderator for all write operations.
 */

import { db } from "@/lib/db";
import * as schema from "@/lib/db/schema";
import { isModerator, requireAuth } from "@/server/auth-utils";
import { invalidateAfterBookOrCopyMutation } from "@/server/cache-invalidation";
import {
  deleteBook,
  getBookById,
  insertBook,
  updateBook,
} from "@/lib/db/queries/books";
import {
  deleteCopy,
  getCopyById,
  getBorrowedCopiesCountByBookId,
  getMaxCopyNumber,
  insertCopy,
  updateCopy,
} from "@/lib/db/queries/copies";
import { logActionError } from "@/server/error-log";
import { and, eq, inArray, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";

// ─────────────────────────────────────────────────────────────────────────────
// Auth helper
// ─────────────────────────────────────────────────────────────────────────────

async function requireModOrAdmin() {
  const user = await requireAuth();
  const mod = await isModerator();
  if (!mod) throw new Error("Insufficient permissions");
  return user;
}

// ─────────────────────────────────────────────────────────────────────────────
// Books
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Add a new book. Optionally creates the first copy in the same action.
 *
 * FormData fields:
 *   title (required), author (required), is_syllabus ("true"|"false"),
 *   pages (number, optional), pdf_link (optional),
 *   first_copy_id (QR text, optional — creates copy 1 if provided)
 */
export async function addBook(
  formData: FormData,
): Promise<{ error?: string; bookId?: string }> {
  try {
    const user = await requireModOrAdmin();

    const title = (formData.get("title") as string)?.trim();
    const author = (formData.get("author") as string)?.trim();
    const category_id = (formData.get("category_id") as string) || null;
    const is_syllabus = formData.get("is_syllabus") === "true";
    const pagesRaw = parseInt(formData.get("pages") as string, 10);
    const pages = Number.isFinite(pagesRaw) && pagesRaw > 0 ? pagesRaw : null;
    const pdf_link = (formData.get("pdf_link") as string)?.trim() || null;
    const first_copy_id = (formData.get("first_copy_id") as string)?.trim().toUpperCase();

    if (!title) return { error: "Title is required" };
    if (!author) return { error: "Author is required" };

    // Check for duplicate copy ID if provided
    if (first_copy_id) {
      const existingCopy = await getCopyById(first_copy_id);
      if (existingCopy) {
        return { error: `A copy with ID "${first_copy_id}" already exists` };
      }
    }

    // Book ID is auto-generated by the database
    const [book] = await insertBook({
      title,
      author,
      category_id,
      is_syllabus,
      pages,
      pdf_link,
    });

    if (!book) {
      throw new Error("Failed to add book");
    }

    if (first_copy_id) {
      try {
        await insertCopy({ id: first_copy_id, book_id: book.id, copy_number: 1 });
      } catch (copyErr: any) {
        const msg = `Book added but failed to create first copy: ${copyErr.message}`;
        logActionError("addBook", msg, user.id, { bookId: book.id, first_copy_id });
        invalidateAfterBookOrCopyMutation();
        revalidatePath("/dashboard/books");
        return { bookId: book.id, error: msg };
      }
    }

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return { bookId: book.id };
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Edit an existing book's metadata (title, author, is_syllabus, pages, pdf_link).
 *
 * FormData fields: id (required), title, author, is_syllabus, pages, pdf_link
 */
export async function editBook(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    const user = await requireModOrAdmin();

    const id = (formData.get("id") as string)?.toUpperCase();
    const title = (formData.get("title") as string)?.trim();
    const author = (formData.get("author") as string)?.trim();
    const category_id = (formData.get("category_id") as string) || null;
    const is_syllabus = formData.get("is_syllabus") === "true";
    const pagesRaw = parseInt(formData.get("pages") as string, 10);
    const pages = Number.isFinite(pagesRaw) && pagesRaw > 0 ? pagesRaw : null;
    const pdf_link = (formData.get("pdf_link") as string)?.trim() || null;

    if (!id) return { error: "Book ID is required" };
    if (!title) return { error: "Title is required" };
    if (!author) return { error: "Author is required" };

    await updateBook(id, { title, author, category_id, is_syllabus, pages, pdf_link });

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return {};
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Delete a book and all its copies (cascades via FK).
 * Will fail if any copy is currently borrowed.
 *
 * FormData fields: id (required)
 */
export async function removeBook(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    const user = await requireModOrAdmin();

    const id = (formData.get("id") as string)?.toUpperCase();
    if (!id) return { error: "Book ID is required" };

    // Safety: block if any copy is currently borrowed
    const borrowedCount = await getBorrowedCopiesCountByBookId(id);

    if (borrowedCount > 0) {
      const msg = "Cannot delete: one or more copies are currently borrowed";
      logActionError("removeBook", msg, user.id, { bookId: id });
      return { error: msg };
    }

    await deleteBook(id);

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return {};
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Returns the number of active/pending transactions for a book.
 */
export async function getBookRefCount(bookId: string): Promise<number> {
  const result = await db.query.transactions.findMany({
    where: and(
      eq(schema.transactions.book_id, bookId),
      inArray(schema.transactions.status, ["pending", "active", "overdue"])
    ),
    columns: { id: true },
  });
  return result.length;
}

/**
 * Returns the total number of transactions for a specific copy.
 * Used to warn about data inconsistency before deletion.
 */
export async function getCopyRefCount(copyId: string): Promise<number> {
  const result = await db.query.transactions.findMany({
    where: eq(schema.transactions.copy_id, copyId),
    columns: { id: true },
  });
  return result.length;
}

/**
 * Returns the number of people currently borrowing this book (active/overdue only).
 * Used to block book deletion and show the borrower count message.
 */
export async function getActiveBorrowersForBook(bookId: string): Promise<number> {
  const result = await db.query.transactions.findMany({
    where: and(
      eq(schema.transactions.book_id, bookId),
      eq(schema.transactions.type, "borrow"),
      inArray(schema.transactions.status, ["active", "overdue"])
    ),
    columns: { id: true },
  });
  return result.length;
}

/**
 * Returns the full name of the person currently borrowing a specific copy,
 * or null if nobody is borrowing it.
 */
export async function getCopyBorrowerName(copyId: string): Promise<string | null> {
  const tx = await db.query.transactions.findFirst({
    where: and(
      eq(schema.transactions.copy_id, copyId),
      eq(schema.transactions.type, "borrow"),
      inArray(schema.transactions.status, ["active", "overdue"])
    ),
    with: {
      user: { columns: { full_name: true } },
    },
  });
  return tx?.user?.full_name ?? null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Categories
// ─────────────────────────────────────────────────────────────────────────────

export async function addCategory(formData: FormData) {
  try {
    await requireModOrAdmin(); // User said "Admins only" but let's see. Wait, "from the UI by Admins only".
    // I should check for Admin specifically if the user said so.
  } catch (err) {
    return { error: "Unauthorized" };
  }

  const name = (formData.get("name") as string)?.trim();
  const count_in_progress = formData.get("count_in_progress") === "true";

  if (!name) return { error: "Name is required" };

  try {
    await db.insert(schema.categories).values({ name, count_in_progress });
    revalidatePath("/dashboard/categories");
    return {};
  } catch (err: any) {
    return { error: err.message };
  }
}

export async function editCategory(formData: FormData) {
  try {
    await requireModOrAdmin();
  } catch (err) {
    return { error: "Unauthorized" };
  }

  const id = formData.get("id") as string;
  const name = (formData.get("name") as string)?.trim();
  const count_in_progress = formData.get("count_in_progress") === "true";

  if (!id || !name) return { error: "ID and Name are required" };

  try {
    await db
      .update(schema.categories)
      .set({ name, count_in_progress, updated_at: new Date() })
      .where(eq(schema.categories.id, id));
    revalidatePath("/dashboard/categories");
    return {};
  } catch (err: any) {
    return { error: err.message };
  }
}

export async function removeCategory(formData: FormData) {
  try {
    await requireModOrAdmin();
  } catch (err) {
    return { error: "Unauthorized" };
  }

  const id = formData.get("id") as string;
  if (!id) return { error: "ID is required" };

  try {
    await db.delete(schema.categories).where(eq(schema.categories.id, id));
    revalidatePath("/dashboard/categories");
    return {};
  } catch (err: any) {
    return { error: err.message };
  }
}

export async function getCategoryRefCount(categoryId: string) {
  const [bookCount] = await db
    .select({ count: sql<number>`count(*)` })
    .from(schema.books)
    .where(eq(schema.books.category_id, categoryId));

  const [profileCount] = await db
    .select({ count: sql<number>`count(*)` })
    .from(schema.profiles)
    .where(eq(schema.profiles.category_id, categoryId));

  return {
    books: Number(bookCount?.count ?? 0),
    profiles: Number(profileCount?.count ?? 0),
  };
}

/**
 * Add a new physical copy of an existing book.
 * The copy_number is auto-incremented based on existing copies.
 *
 * FormData fields: book_id (UUID), copy_id (QR text, unique)
 */
export async function addCopyOfBook(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    const user = await requireModOrAdmin();

    const book_id = (formData.get("book_id") as string)?.toUpperCase();
    const copy_id = (formData.get("copy_id") as string)?.trim().toUpperCase();

    if (!book_id) return { error: "Book ID is required" };
    if (!copy_id) return { error: "Copy ID is required" };

    const book = await getBookById(book_id);
    if (!book) return { error: "Book not found" };

    // Check for duplicate copy ID
    const existingCopy = await getCopyById(copy_id);
    if (existingCopy) {
      return { error: `A copy with ID "${copy_id}" already exists` };
    }

    // Get max copy number to increment it for this book
    const copy_number = (await getMaxCopyNumber(book_id)) + 1;

    try {
      await insertCopy({ id: copy_id, book_id, copy_number, status: "available" });

      invalidateAfterBookOrCopyMutation();
      revalidatePath("/dashboard/books");
      revalidatePath("/dashboard/copies");
      return {};
    } catch (err: any) {
      if (err.message?.includes("unique") || err.code === "23505") {
        return { error: `Copy ID "${copy_id}" is already in use` };
      }
      throw err;
    }
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Delete a single copy.
 * Fails if the copy is currently borrowed.
 */
export async function removeCopy(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    const user = await requireModOrAdmin();

    const id = ((formData.get("copy_id") as string) || (formData.get("id") as string))?.toUpperCase();
    if (!id) return { error: "Copy ID is required" };

    const copy = await getCopyById(id);
    if (!copy) return { error: "Copy not found" };

    if (copy.status === "borrowed") {
      return { error: "Cannot delete a borrowed copy" };
    }

    await deleteCopy(id);

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return {};
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Change status or other metadata of a copy.
 */
export async function updateCopyMetadata(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    const user = await requireModOrAdmin();

    const id = (formData.get("id") as string)?.toUpperCase();
    const status = formData.get("status") as string;

    if (!id) return { error: "Copy ID is required" };
    if (!status) return { error: "Status is required" };

    await updateCopy(id, { status });

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return {};
  } catch (error: any) {
    return { error: error.message };
  }
}

/**
 * Rename a copy's ID (primary key).
 * Updates the copy row and all related transaction rows atomically.
 *
 * FormData fields: old_id (required), new_id (required)
 */
export async function renameCopyId(
  formData: FormData,
): Promise<{ error?: string }> {
  try {
    await requireModOrAdmin();

    const oldId = (formData.get("old_id") as string)?.trim().toUpperCase();
    const newId = (formData.get("new_id") as string)?.trim().toUpperCase();

    if (!oldId) return { error: "Old Copy ID is required" };
    if (!newId) return { error: "New Copy ID is required" };
    if (oldId === newId) return { error: "New ID is the same as the current ID" };

    // Ensure the copy exists
    const existing = await getCopyById(oldId);
    if (!existing) return { error: "Copy not found" };

    // Check for collision
    const collision = await getCopyById(newId);
    if (collision) return { error: `A copy with ID "${newId}" already exists` };

    // Rename atomically: update copies PK then cascade to transactions
    await db.transaction(async (tx) => {
      // 1. Insert the copy with the new ID
      await tx.insert(schema.copies).values({
        id: newId,
        book_id: existing.book_id,
        copy_number: existing.copy_number,
        status: existing.status,
        created_at: existing.created_at,
        updated_at: new Date(),
      });

      // 2. Re-point all transactions to the new copy ID
      await tx
        .update(schema.transactions)
        .set({ copy_id: newId })
        .where(eq(schema.transactions.copy_id, oldId));

      // 3. Delete the old copy row (transactions no longer reference it)
      await tx.delete(schema.copies).where(eq(schema.copies.id, oldId));
    });

    invalidateAfterBookOrCopyMutation();
    revalidatePath("/dashboard/books");
    revalidatePath("/dashboard/copies");
    return {};
  } catch (error: any) {
    return { error: error.message };
  }
}
